import "@/styles/globals.css";
import { ProvidersWithoutTheme } from "@/components/providers/providers-without-theme";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import * as React from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/assets/icon_white.png" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${GeistSans.variable}`}>
      <body className="relative min-h-screen bg-background">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ProvidersWithoutTheme>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </ProvidersWithoutTheme>
        </ThemeProvider>
      </body>
    </html>
  );
}
