import "@/styles/globals.css";
import { ProvidersWithoutTheme } from "@/components/providers/providers-without-theme";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import * as React from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="relative min-h-screen bg-background">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ProvidersWithoutTheme>
            <div className="absolute -z-50 h-full w-full bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)]" />
            {children}
          </ProvidersWithoutTheme>
        </ThemeProvider>
      </body>
    </html>
  );
}
